USE [master]
GO

/****** Object:  Database [DVDLibrary]    Script Date: 11/10/2015 2:46:57 PM ******/
CREATE DATABASE [DVDLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DVDLibrary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\DVDLibrary.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DVDLibrary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\DVDLibrary_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DVDLibrary] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DVDLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DVDLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DVDLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DVDLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DVDLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DVDLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [DVDLibrary] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DVDLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DVDLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DVDLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DVDLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DVDLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DVDLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DVDLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DVDLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DVDLibrary] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DVDLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DVDLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DVDLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DVDLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DVDLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DVDLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DVDLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DVDLibrary] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DVDLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [DVDLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DVDLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DVDLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DVDLibrary] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DVDLibrary] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DVDLibrary] SET  READ_WRITE 
GO

